services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecomerce-apache-php
    container_name: apache-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DATABASE=mibd
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=nuns2272@gmail.com
      - SMTP_PASSWORD=jlcm vthl oulp bwxp
      - SMTP_ENCRYPTION=tls
      - SMTP_FROM_EMAIL=nuns2272@gmail.com
      - SMTP_FROM_NAME=ecommerce
    depends_on:
      - mysql
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mibd
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - mysql
    networks:
      - webnet

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - webnet

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./html:/app
    working_dir: /app
    networks:
      - webnet
    command: tail -f /dev/null

volumes:
  mysql-data:

networks:
  webnet:
    driver: bridge